# -*- coding: utf-8 -*-
"""SQL_Query_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vM4ENOAB4mYLm2sdbudXZnNBcXwhCGxO
"""

!pip install -q gradio transformers torch reportlab requests

import gradio as gr
import sqlite3
import re
import torch
import datetime
import urllib.parse
from transformers import AutoTokenizer, AutoModelForCausalLM
from reportlab.pdfgen import canvas

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

print("Model Loaded Successfully")

SCHEMA = {
    "users": ["id", "name", "email", "signup_date", "age", "country", "status"],
    "orders": ["id", "user_id", "product_name", "amount", "order_date", "status"],
    "products": ["id", "name", "price", "category", "stock"],
    "transactions": ["id", "user_id", "amount", "date", "type"]
}

DANGEROUS_KEYWORDS = [
    "DROP", "DELETE", "ALTER", "TRUNCATE",
    "INSERT", "UPDATE", "EXEC", "EXECUTE"
]

DANGEROUS_PATTERNS = [
    ";",
    "--",
    "/*",
    "*/",
    "xp_",
    "sp_"
]

def is_safe(text):
    text_upper = text.upper()

    for keyword in DANGEROUS_KEYWORDS:
        if keyword in text_upper:
            return False

    for pattern in DANGEROUS_PATTERNS:
        if pattern in text:
            return False

    return True

def get_table_name(text):

    text = text.lower()

    if any(word in text for word in ["user","users","customer","account"]):
        return "users"

    if any(word in text for word in ["order","orders","purchase"]):
        return "orders"

    if any(word in text for word in ["product","products","item"]):
        return "products"

    if any(word in text for word in ["transaction","payment"]):
        return "transactions"

    return "users"

def get_column_names(text):

    columns = []

    mapping = {
        "name":["name","username"],
        "email":["email","mail"],
        "signup_date":["signup","joined","registered"],
        "age":["age","years"],
        "amount":["amount","price","cost"],
        "status":["status","state"],
        "country":["country","location"]
    }

    for column,keywords in mapping.items():
        if any(k in text.lower() for k in keywords):
            columns.append(column)

    if not columns:
        columns.append("*")

    return columns

def extract_conditions(text):

    conditions = []

    amount_match = re.search(r'greater than (\d+)',text)

    if amount_match:
        conditions.append(f"amount > {amount_match.group(1)}")

    if "last week" in text:
        conditions.append("DATE(date) >= DATE('now','-7 days')")

    if "last month" in text:
        conditions.append("DATE(signup_date) >= DATE('now','-1 month')")

    return conditions

def generate_sql(text):

    if not is_safe(text):
        return "Security Error: Unsafe query detected"

    table = get_table_name(text)

    columns = ",".join(get_column_names(text))

    conditions = extract_conditions(text)

    query = f"SELECT {columns} FROM {table}"

    if conditions:
        query += " WHERE " + " AND ".join(conditions)

    query += " LIMIT 10"

    return query

query_history = []

def export_pdf():

    filename = "queries.pdf"

    c = canvas.Canvas(filename)

    y = 800

    for i,q in enumerate(query_history):
        c.drawString(50,y,f"{i+1}. {q}")
        y -= 30

    c.save()

    return filename

def whatsapp_share():

    text = "\n".join(query_history[-5:])

    encoded = urllib.parse.quote(text)

    link = f"https://wa.me/?text={encoded}"

    return link

def chat(user_input):

    sql = generate_sql(user_input)

    query_history.append(sql)

    return sql

with gr.Blocks() as demo:

    gr.Markdown("# SQL Query Generator")

    user_input = gr.Textbox(label="Enter your query")

    output = gr.Textbox(label="Generated SQL")

    btn = gr.Button("Generate SQL")

    btn.click(chat,inputs=user_input,outputs=output)

demo.launch(share=True)